{ config }:
let
  developmentBashCommands = [
    "cargo build*"
    "cargo fmt*"
    "cargo clippy*"
    "cargo check*"
    "cargo test*"
    "cargo nextest run*"
    "rustfmt*"
    "cabal build*"
    "cabal check*"
    "cabal test*"
    "cabal v2-test*"
    "stack test*"
    "hlint*"
    "ormolu*"
    "fourmolu*"
    "stylish-haskell*"
    "cabal-fmt*"
    "nix fmt*"
    "nixpkgs-fmt*"
    "alejandra*"
    "treefmt*"
    "statix check*"
    "deadnix*"
    "shellcheck*"
    "shfmt*"
    "nixfmt*"
    "ruff format --check*"
    "command -v *"
  ];

  wrappedDevelopmentBashCommands = builtins.concatMap
    (command: [
      "nix develop --command ${command}"
      "nix develop .#* --command ${command}"
      "nix develop ${config.home.homeDirectory}/Code/conf-update-* --command ${command}"
      "nix develop -c ${command}"
      "nix develop .#* -c ${command}"
      "nix develop ${config.home.homeDirectory}/Code/conf-update-* -c ${command}"
      "direnv exec . ${command}"
    ])
    developmentBashCommands;

  trustedNixRunApps = [
    "codex-unresolved-comments"
    "codex-unresolved-threads"
    "panharmonicon-cabal2nix-check"
    "panharmonicon-cabal2nix-generate"
    "pr-ci-failed-logs"
    "pr-ready-wait"
    "precommit-check"
    "prod-monolith-log"
    "src-fix"
  ];

  trustedNixRunBashCommands = builtins.concatMap
    (app: [
      "nix run .#${app}"
      "nix run .#${app} *"
    ])
    trustedNixRunApps;

  linearisReadOnlyBashCommands = [
    "linearis -V"
    "linearis --version"
    "linearis --help*"
    "linearis usage*"
    "linearis version"
    "linearis version check*"
    "linearis version usage*"
    "linearis auth --help*"
    "linearis auth status*"
    "linearis auth usage*"
    "linearis issues --help*"
    "linearis issues list*"
    "linearis issues search*"
    "linearis issues read*"
    "linearis issues activity*"
    "linearis issues discussions*"
    "linearis issues replies*"
    "linearis issues relations --help*"
    "linearis issues relations list*"
    "linearis issues usage*"
    "linearis comments --help*"
    "linearis comments list*"
    "linearis comments usage*"
    "linearis labels --help*"
    "linearis labels list*"
    "linearis labels read*"
    "linearis labels usage*"
    "linearis projects --help*"
    "linearis projects list*"
    "linearis projects read*"
    "linearis projects discussions*"
    "linearis projects replies*"
    "linearis projects usage*"
    "linearis cycles --help*"
    "linearis cycles list*"
    "linearis cycles read*"
    "linearis cycles usage*"
    "linearis milestones --help*"
    "linearis milestones list*"
    "linearis milestones read*"
    "linearis milestones usage*"
    "linearis files --help*"
    "linearis files usage*"
    "linearis attachments --help*"
    "linearis attachments list*"
    "linearis attachments usage*"
    "linearis teams --help*"
    "linearis teams list*"
    "linearis teams read*"
    "linearis teams members*"
    "linearis teams usage*"
    "linearis users --help*"
    "linearis users list*"
    "linearis users usage*"
    "linearis initiatives --help*"
    "linearis initiatives list*"
    "linearis initiatives read*"
    "linearis initiatives discussions*"
    "linearis initiatives replies*"
    "linearis initiatives updates --help*"
    "linearis initiatives updates list*"
    "linearis initiatives updates read*"
    "linearis initiatives usage*"
    "linearis documents --help*"
    "linearis documents list*"
    "linearis documents read*"
    "linearis documents usage*"
  ];

  gcloudReadOnlyBashCommands = [
    "gcloud -h*"
    "gcloud --help*"
    "gcloud --version*"
    "gcloud help*"
    "gcloud info*"
    "gcloud topic*"
    "gcloud version*"
    "gcloud * --help*"
    "gcloud * help*"
    "gcloud * list"
    "gcloud * list *"
    "gcloud * describe"
    "gcloud * describe *"
    "gcloud * get-iam-policy"
    "gcloud * get-iam-policy *"
    "gcloud asset search-all-iam-policies*"
    "gcloud asset search-all-resources*"
    "gcloud auth list*"
    "gcloud config get-value*"
    "gcloud storage du*"
    "gcloud storage cat*"
    "gcloud storage ls*"
  ];

  ghReadOnlyBashCommands = [
    "gh --help*"
    "gh --version*"
    "gh auth status*"
    "gh status*"
    "gh pr checks*"
    "gh pr diff*"
    "gh pr list*"
    "gh pr status*"
    "gh pr view*"
    "gh issue list*"
    "gh issue status*"
    "gh issue view*"
    "gh repo list*"
    "gh repo view*"
    "gh run list*"
    "gh run view*"
    "gh run watch*"
    "gh workflow list*"
    "gh workflow view*"
    "gh release list*"
    "gh release view*"
    "gh search code*"
    "gh search commits*"
    "gh search issues*"
    "gh search prs*"
    "gh search repos*"
  ];

  allowedBashCommands = [
    "ls*"
    "rg*"
    "find*"
    "grep*"
    "cat*"
    "head*"
    "tail*"
    "wc*"
    "sort*"
    "uniq*"
    "cut*"
    "base64*"
    "tree*"
    "file*"
    "cmp*"
    "diff*"
    "stat*"
    "du*"
    "df*"
    "ps*"
    "which*"
    "type*"
    "whereis*"
    "locate*"
    "basename*"
    "dirname*"
    "realpath*"
    "readlink*"
    "pwd"
    "pwd -*"
    "id"
    "id *"
    "uname"
    "uname *"
    "hostname"
    "hostname -f"
    "hostname -s"
    "hostnamectl hostname"
    "lspci*"
    "pgrep*"
    "getent *"
    "sha256sum *"
    "comm *"
    "date*"
    "sleep *"
    "echo*"
    "printf*"
    "notify-send *"
    "true"
    "test*"
    "expr*"
    "jq*"
    "git status*"
    "git log*"
    "git diff*"
    "git show*"
    "git branch*"
    "git remote*"
    "git rev-parse*"
    "git ls-files*"
    "git ls-remote*"
    "git ls-tree*"
    "git grep*"
    "git check-ignore*"
    "git rev-list*"
    "git for-each-ref*"
    "git reflog"
    "git reflog show*"
    "git cat-file*"
    "git diff-tree*"
    "git hash-object*"
    "git range-diff*"
    "git patch-id*"
    "git worktree list*"
    "git worktree add --no-track -b update-* ${config.home.homeDirectory}/Code/conf-update-* HEAD"
    "git worktree add ${config.home.homeDirectory}/Code/conf-update-* update-*"
    "git config --get*"
    "git config --list*"
    "git blame*"
    "git merge-base*"
    "git describe*"
    "git tag"
    "git tag --list*"
    "git clone --filter=blob:none --no-checkout * /tmp/flake-update/*"
    "git -C /tmp/flake-update/* fetch*"
    "git -C /tmp/flake-update/* checkout --detach*"
    "git -C /tmp/flake-update/* worktree add --detach /tmp/flake-update/*"
    "gh api*"
    "gh repo clone * /tmp/flake-update/* -- --no-checkout"
    "bash -n *"
    "direnv reload"
    "direnv status*"
    "opencode --help*"
    "opencode --version*"
    "opencode1 --help*"
    "opencode1 --version*"
    "opencode2 --help*"
    "opencode2 --version*"
    "nix eval*"
    "nix build*"
    "nix log*"
    "nix derivation show*"
    "nix show-derivation*"
    "nix path-info*"
    "nix why-depends*"
    "nix show-config*"
    "nix hash*"
    "nix search*"
    "nix flake show*"
    "nix flake metadata*"
    "nix flake check*"
    "nix flake update*"
    "nix store ls*"
    "nix store cat*"
    "nix store diff-closures*"
    "nix store ping*"
    "nix store verify*"
    "nix-store -q*"
    "nix-store --query*"
    "flake-update*"
    "flake-changelog*"
    "nixpkgs-changelog*"
    "nh os build*"
    "nh os test*"
    "nh --version*"
    "nh * --help*"
    "just build*"
    "just fmt*"
    "just test*"
    "just health*"
    "just vim-health*"
    "just gnome-check*"
    "just test-remote-builds*"
    "nvd diff*"
    "got-gnomed*"
    "systemctl --failed*"
    "systemctl status*"
    "systemctl show*"
    "systemctl cat*"
    "systemctl list-units*"
    "systemctl list-unit-files*"
    "systemctl list-timers*"
    "systemctl is-active*"
    "systemctl is-enabled*"
    "systemctl --user status*"
    "systemctl --user show*"
    "systemctl --user cat*"
    "systemctl --user list-units*"
    "systemctl --user list-unit-files*"
    "systemctl --user list-timers*"
    "systemctl --user is-active*"
    "systemctl --user is-enabled*"
    "journalctl -p*"
    "journalctl -u * -b --no-pager -n *"
    "journalctl --user -u meridian --no-pager*"
    "tmux show-environment*"
    "tmux display-message*"
    "podman ps*"
    "sudo podman inspect --format '{{.State.Health.Status}}' foundryvtt"
    "sudo podman healthcheck run foundryvtt"
    "curl -sS http://127.0.0.1:3456/health"
    "meridian --version*"
    "check-syncthing*"
    "ssh -o ConnectTimeout=5 torag echo*"
    "ssh -o BatchMode=yes -o ConnectTimeout=15 torag 'hostname; uptime -p'"
    "ssh -o BatchMode=yes -o ConnectTimeout=10 torag 'hostname; readlink /run/current-system'"
    "ssh -o BatchMode=yes -o ConnectTimeout=10 am 'hostname; readlink /run/current-system'"
    "ssh torag just health*"
    "ssh torag just vim-health*"
    "ssh torag just gnome-check*"
    "ssh torag just test-remote-builds*"
  ]
  ++ developmentBashCommands
  ++ wrappedDevelopmentBashCommands
  ++ trustedNixRunBashCommands
  ++ linearisReadOnlyBashCommands
  ++ ghReadOnlyBashCommands
  ++ gcloudReadOnlyBashCommands;

in
{
  external_directory = {
    "/nix/store/**" = "allow";
    "/tmp/**" = "allow";
    "${config.home.homeDirectory}/Code/conf-update-*/**" = "allow";
  };
  lsp = "allow";
  # Slack MCP: reads are allowed by default; anything that publishes asks first.
  # Drafts stay allowed — they are the review-first posting workflow.
  "slack_slack_send_message" = "ask";
  "slack_slack_schedule_message" = "ask";
  "slack_slack_add_reaction" = "ask";
  "slack_slack_create_conversation" = "ask";
  "slack_slack_create_canvas" = "ask";
  "slack_slack_update_canvas" = "ask";
  read = {
    "/nix/store/**" = "allow";
    "/tmp/**" = "allow";
  };
  bash = builtins.listToAttrs (
    [
      {
        name = "*";
        value = "ask";
      }
    ]
    ++ map
      (command: {
        name = command;
        value = "allow";
      })
      allowedBashCommands
  );
  edit = {
    "*" = "ask";
    "/nix/store/**" = "deny";
    "/tmp/**" = "allow";
  };
}
