#!/bin/sh

# xinitrc runs automatically when you run startx.


xrandr --output HDMI-1      --mode 1920x1080 --rate 60
xrandr --output DP-3 --mode 1920x1080 --rate 60 --right-of HDMI-1

#xrdb ~/.Xrescources


feh --randomize --bg-fill ~/Pictures/Wallpapers/ &
picom &

#if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
#	eval $(dbus-launch --exit-with-session --sh-syntax)
#fi
#
#systemctl --user import-environment DISPLAY XAUTHORITY
#
#if command -v dbus-update-activation-environment >/dev/null 2>&1; then
#        dbus-update-activation-environment DISPLAY XAUTHORITY
#fi

dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY


#dbus-launch breaks steam somehow?
#exec ${WM:-xmonad}
exec dbus-launch ${WM:-xmonad}
