echo "=== GTD OVERVIEW ==="
echo ""
echo "Inbox:       $(task status:pending -next -waiting -someday count) tasks"
echo "Next:        $(task +next status:pending count) tasks"
echo "Waiting:     $(task +waiting status:pending count) tasks"
echo "Someday:     $(task +someday status:pending count) tasks"
echo ""
echo "Total pending: $(task status:pending count) tasks"
echo "Completed this week: $(task status:completed end.after:today-7days count) tasks"
